### ISSUE TITLE
tao can't compile in 0.30.7 under android

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/tao#1011]
**Describe the bug**

Try cargo building a project with tao 0.30.7 and under android. It simply won't compile.

```
error[E0308]: mismatched types
   --> /Users/jonkelley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.7/src/platform_impl/android/mod.rs:715:12
    |
715 |     if let Some(w) = ndk_glue::window_manager() {
    |            ^^^^^^^   -------------------------- this expression has type `Ref<'_, std::option::Option<GlobalRef>>`
    |            |
    |            expected `Ref<'_, Option<GlobalRef>>`, found `Option<_>`
    |
    = note: expected struct `Ref<'_, std::option::Option<GlobalRef>, >`
                 found enum `std::option::Option<_>`
```

I highly suggest adding Android to CI.

This is semver breaking and broke CI for Dioxus.

**Comment by amrbashir** [comment]
Seems like an issue only when `rwh_04` or `rwh_05` feature flags are activated which is indeed not tested in CI, I will release a fix shortly
