### ISSUE TITLE
Fails to build on aarch64 (v0.26.0)

### ISSUE THREAD

**Issue by thenbe** [tauri-apps/tao#883]
**Describe the bug**
Error when building on aarch64

```text
   Compiling tao v0.26.0
   Compiling muda v0.11.5
error[E0308]: mismatched types
  --> /build/cargo-vendor-dir/tao-0.26.0/src/platform_impl/linux/taskbar.rs:69:81
   |
69 |         let handle = unsafe { unity_lib.unity_launcher_entry_get_for_desktop_id(id.as_ptr()) };
   |                                         --------------------------------------- ^^^^^^^^^^^ expected `*const i8`, found `*const u8`
   |                                         |
   |                                         arguments to this method are incorrect
   |
   = note: expected raw pointer `*const i8`
              found raw pointer `*const u8`
note: method defined here
  --> /build/cargo-vendor-dir/tao-0.26.0/src/platform_impl/linux/taskbar.rs:9:3
   |
9  |   unity_launcher_entry_get_for_desktop_id: unsafe extern "C" fn(id: *const i8) -> *const isize,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                       -------------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tao` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
       Error [tauri_cli_node] failed to build app: failed to build app
task: Failed to run task "build": exit status 1
```

**Platform and Versions (please complete the following information):**

```
 rustc 1.78.0-nightly (a4472498d 2024-02-15)

 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.426.afc48694f2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

The build IS OK on my intel system (also nixOS, using the same flake).
